### ISSUE TITLE
[pgr_edgeColoring] Changing ordering of the edges gives difference in number of colors required

### ISSUE THREAD

**Issue by veenits123** [veenits123/pgrouting#1]
Problem: https://github.com/pgRouting/pgrouting/blob/a49ff1b5612390661abafc27b45b85469f694242/pgtap/coloring/edgeColoring/edge-cases.sql#L131

**Comment by cvvergara** [comment]
https://github.com/pgRouting/pgrouting/blob/develop/pgtap/coloring/edgeColoring/edge-cases.sql#L131
I had to change the test to be a '<=' compare, because of the expected value si to be 2 (two) forgot the w on the comment
That query use the table created

PREPARE q6 AS
SELECT id, source, target, cost, reverse_cost
FROM edge_table
WHERE id IN (8, 10, 11, 12);

So, lets use edge coloring:
Vicky Vergara
@cvvergara
11:04
This gives 3 colors total

SELECT * from pgr_edgeColoring('SELECT id, source, target, cost, reverse_cost
FROM edge_table
WHERE id IN (8, 10, 11, 12)');
 edge_id | color_id 
---------+----------
       8 |        1
      10 |        3
      11 |        3
      12 |        2
(4 rows)

This gives 2 colors total: (same query but different ordering on the input data

SELECT * from pgr_edgeColoring('SELECT id, source, target, cost, reverse_cost
FROM edge_table
WHERE id IN (8, 10, 11, 12) ORDER BY id DESC');
 edge_id | color_id 
---------+----------
      12 |        1
      11 |        2
      10 |        2
       8 |        1
(4 rows)

So I was looking on the internet
(looking for the link)
Vicky Vergara
@cvvergara
11:10
cant find the link :-(
I got into another place and found the concept of "Minimum edge coloring"
https://mathworld.wolfram.com/MinimumEdgeColoring.html
So that is different to just plain "edge coloring"
So, maybe the minimum is 2, and 3 is a valid number of colors
But, my mental problem is that its the same graph, and data is just given in a different order and the results are different
Vicky Vergara
@cvvergara
11:16
So, the first step to define if it is a boost graph problem is to directly make the test using boost
If this can be modified to use that unit test with both orderings and if 2 and 3 colors are result of that, then it is not our problem :-)
https://www.boost.org/doc/libs/1_61_0/libs/graph/example/edge_coloring.cpp
Our problem becomes then to document that with different order different number of colors can be obtained
and then probably verify that info with the boost people.
Vicky Vergara
@cvvergara
11:22
Maybe re-read the paper from Mista (forgot the real spelling of that name)

**Comment by cvvergara** [comment]
Reading your documentation and found this:
> At most **Δ + 1** colors are used, where **Δ** is the degree of the graph. This is optimal for some graphs, and by Vizing's theorem it uses at most one color more than the optimal for all others.

**Comment by veenits123** [comment]
It is Boost Graph Problem, I have tested their original C++ code from here: https://www.boost.org/doc/libs/1_61_0/libs/graph/example/edge_coloring.cpp

and it is giving us the same result like **if the Ordering of edges are changed the number of colors required is also changed**.

This is giving 3 colors:
```c++
#include <boost/config.hpp>
#include <boost/graph/adjacency_list.hpp>
#include <boost/graph/edge_coloring.hpp>
#include <boost/graph/properties.hpp>
#include <iostream>

using namespace boost;
using namespace std;

int main(int, char*[]) {

    typedef adjacency_list<vecS, vecS, undirectedS, no_property, size_t,
            no_property>
            Graph;

    typedef std::pair<std::size_t, std::size_t> Pair;
    Pair edges[4] = {Pair(5, 6),
                     Pair(5, 10),
                     Pair(6, 11),
                     Pair(10, 11)
                    };

    Graph G(10);

    for (size_t i = 0; i < sizeof(edges) / sizeof(edges[0]); i++)
        add_edge(edges[i].first, edges[i].second, G);

    size_t colors = edge_coloring(G, get(edge_bundle, G));

    cout << "Colored using " << colors << " colors" << endl;
    for (size_t i = 0; i < sizeof(edges) / sizeof(edges[0]); i++) {
        cout << "  " << edges[i].first << "-"
             << edges[i].second << ": "
             << G[edge(edges[i].first, edges[i].second, G).first] + 1 << endl;
    }

    return 0;
}
```
And the output like:
```
Colored using 3 colors
  5-6: 1
  5-10: 3
  6-11: 3
  10-11: 2

```


The same code but different ordering of edges, this gives 2 colors:
  
```c++
#include <boost/config.hpp>
#include <boost/graph/adjacency_list.hpp>
#include <boost/graph/edge_coloring.hpp>
#include <boost/graph/properties.hpp>
#include <iostream>

using namespace boost;
using namespace std;

int main(int, char*[]) {

    typedef adjacency_list<vecS, vecS, undirectedS, no_property, size_t,
            no_property>
            Graph;

    typedef std::pair<std::size_t, std::size_t> Pair;
    Pair edges[4] = {Pair(10, 11),
                     Pair(6, 11),
                     Pair(5, 10),
                     Pair(5, 6)
                    };

    Graph G(10);

    for (size_t i = 0; i < sizeof(edges) / sizeof(edges[0]); i++)
        add_edge(edges[i].first, edges[i].second, G);

    size_t colors = edge_coloring(G, get(edge_bundle, G));

    cout << "Colored using " << colors << " colors" << endl;
    for (size_t i = 0; i < sizeof(edges) / sizeof(edges[0]); i++) {
        cout << "  " << edges[i].first << "-"
             << edges[i].second << ": "
             << G[edge(edges[i].first, edges[i].second, G).first] + 1 << endl;
    }

    return 0;
}
```
And Output is like:
```
Colored using 2 colors
  10-11: 1
  6-11: 2
  5-10: 2
  5-6: 1

```

**Comment by veenits123** [comment]
> Reading your documentation and found this:
> 
> > At most **Δ + 1** colors are used, where **Δ** is the degree of the graph. This is optimal for some graphs, and by Vizing's theorem it uses at most one color more than the optimal for all others.

Yeah, the **optimal number of colors** would be 2 in our case. But it is using 2 in some case and (2+1) = 3 in other.

**Comment by cvvergara** [comment]
Therefore is not a problem, it is expected.
Maybe it would be good to have it on the additional examples section so that it is clear.
Can you make a PR to develop & master with that additional example please

**Comment by veenits123** [comment]
> Therefore is not a problem, it is expected. Maybe it would be good to have it on the additional examples section so that it is clear. Can you make a PR to develop & master with that additional example please

Yeah, sure.

Like, have the additional examples here: https://github.com/pgRouting/pgrouting/blob/a49ff1b5612390661abafc27b45b85469f694242/pgtap/coloring/edgeColoring/edge-cases.sql#L131 ??

**Comment by veenits123** [comment]
> > Therefore is not a problem, it is expected. Maybe it would be good to have it on the additional examples section so that it is clear. Can you make a PR to develop & master with that additional example please
> 
> Yeah, sure.
> 
> Like, have the additional examples here: https://github.com/pgRouting/pgrouting/blob/a49ff1b5612390661abafc27b45b85469f694242/pgtap/coloring/edgeColoring/edge-cases.sql#L131 ??

Hi, @cvvergara 
Any thoughts??
